// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Auth.Jwk;
using Soenneker.Plex.OpenApiClient.Auth.Keys;
using Soenneker.Plex.OpenApiClient.Auth.Nonce;
using Soenneker.Plex.OpenApiClient.Auth.Token;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The jwk property</summary>
        public global::Soenneker.Plex.OpenApiClient.Auth.Jwk.JwkRequestBuilder Jwk
        {
            get => new global::Soenneker.Plex.OpenApiClient.Auth.Jwk.JwkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.Plex.OpenApiClient.Auth.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.Plex.OpenApiClient.Auth.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nonce property</summary>
        public global::Soenneker.Plex.OpenApiClient.Auth.Nonce.NonceRequestBuilder Nonce
        {
            get => new global::Soenneker.Plex.OpenApiClient.Auth.Nonce.NonceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Soenneker.Plex.OpenApiClient.Auth.Token.TokenRequestBuilder Token
        {
            get => new global::Soenneker.Plex.OpenApiClient.Auth.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
