// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors;
using Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Services.Ultrablur
{
    /// <summary>
    /// Builds and executes requests for operations under \services\ultrablur
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UltrablurRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The colors property</summary>
        public global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors.ColorsRequestBuilder Colors
        {
            get => new global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors.ColorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The image property</summary>
        public global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder Image
        {
            get => new global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.UltrablurRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UltrablurRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/services/ultrablur", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.UltrablurRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UltrablurRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/services/ultrablur", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
