// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.Colon.Timeline
{
    /// <summary>
    /// Builds and executes requests for operations under \:\timeline
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimelineRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimelineRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/:/timeline{?bandwidth*,bufferedSize*,bufferedTime*,continuing*,duration*,key*,offline*,playQueueItemID*,ratingKey*,state*,time*,timeStalled*,timeToFirstFrame*,updated*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimelineRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/:/timeline{?bandwidth*,bufferedSize*,bufferedTime*,continuing*,duration*,key*,offline*,playQueueItemID*,ratingKey*,state*,time*,timeStalled*,timeToFirstFrame*,updated*}", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint is hit during media playback for an item. It must be hit whenever the play state changes, or in the absence of a play state change, in a regular fashion (generally this means every 10 seconds on a LAN/WAN, and every 20 seconds over cellular).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelinePostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelinePostResponse?> PostAsTimelinePostResponseAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelinePostResponse> PostAsTimelinePostResponseAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelinePostResponse>(requestInfo, global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelinePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint is hit during media playback for an item. It must be hit whenever the play state changes, or in the absence of a play state change, in a regular fashion (generally this means every 10 seconds on a LAN/WAN, and every 20 seconds over cellular).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsTimelinePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineResponse?> PostAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineResponse> PostAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineResponse>(requestInfo, global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint is hit during media playback for an item. It must be hit whenever the play state changes, or in the absence of a play state change, in a regular fashion (generally this means every 10 seconds on a LAN/WAN, and every 20 seconds over cellular).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// This endpoint is hit during media playback for an item. It must be hit whenever the play state changes, or in the absence of a play state change, in a regular fashion (generally this means every 10 seconds on a LAN/WAN, and every 20 seconds over cellular).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TimelineRequestBuilderPostQueryParameters 
        {
            /// <summary>Bandwidth in kbps as estimated by the client.</summary>
            [QueryParameter("bandwidth")]
            public int? Bandwidth { get; set; }
            /// <summary>Size in kilobytes of data buffered by client.  Omit if computed by `bufferedTime` above</summary>
            [QueryParameter("bufferedSize")]
            public int? BufferedSize { get; set; }
            /// <summary>Amount of time in seconds buffered by client.  Omit if computed by `bufferedSize` below.</summary>
            [QueryParameter("bufferedTime")]
            public int? BufferedTime { get; set; }
            /// <summary>When state is `stopped`, a flag indicating whether or not the client is going to continue playing anothe item.</summary>
            [QueryParameter("continuing")]
            public int? Continuing { get; set; }
            /// <summary>The total duration of the item in ms.</summary>
            [QueryParameter("duration")]
            public int? Duration { get; set; }
            /// <summary>The details key for the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
            /// <summary>Also used by sync clients, used to indicate that a timeline is being synced from being offline, as opposed to being &quot;live&quot;.</summary>
            [QueryParameter("offline")]
            public int? Offline { get; set; }
            /// <summary>If playing media from a play queue, the play queue&apos;s ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("playQueueItemID")]
            public string? PlayQueueItemID { get; set; }
#nullable restore
#else
            [QueryParameter("playQueueItemID")]
            public string PlayQueueItemID { get; set; }
#endif
            /// <summary>The rating key attribute for the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ratingKey")]
            public string? RatingKey { get; set; }
#nullable restore
#else
            [QueryParameter("ratingKey")]
            public string RatingKey { get; set; }
#endif
            /// <summary>The current state of the media.</summary>
            [Obsolete("This property is deprecated, use StateAsPostStateQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>The current state of the media.</summary>
            [QueryParameter("state")]
            public global::Soenneker.Plex.OpenApiClient.Colon.Timeline.PostStateQueryParameterType? StateAsPostStateQueryParameterType { get; set; }
            /// <summary>The current time offset of playback in ms.</summary>
            [QueryParameter("time")]
            public int? Time { get; set; }
            /// <summary>Time in seconds spent buffering since last request.</summary>
            [QueryParameter("timeStalled")]
            public int? TimeStalled { get; set; }
            /// <summary>Time in seconds till first frame is displayed.  Sent only on the first playing timeline request.</summary>
            [QueryParameter("timeToFirstFrame")]
            public int? TimeToFirstFrame { get; set; }
            /// <summary>Used when a sync client comes online and is syncing media timelines, holds the time at which the playback state was last updated.</summary>
            [QueryParameter("updated")]
            public int? Updated { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TimelineRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder.TimelineRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
