// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Hubs.Sections.Item.Manage.Move
{
    /// <summary>Whether this hub is visible on the home screen  - all: Visible to all users  - none: Visible to no users  - admin: Visible to only admin users  - shared: Visible to shared users</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MovePutResponse_MediaContainer_Hub_homeVisibility
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "shared")]
        #pragma warning disable CS1591
        Shared,
        #pragma warning restore CS1591
    }
}
