// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    /// <summary>
    /// A media container representing a play queue.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaContainerWithPlayQueue : global::Soenneker.Plex.OpenApiClient.Models.MediaContainer, IParsable
    {
        /// <summary>The playQueueID property</summary>
        public int? PlayQueueID { get; set; }
        /// <summary>The playQueueLastAddedItemID property</summary>
        public int? PlayQueueLastAddedItemID { get; set; }
        /// <summary>The playQueueSelectedItemID property</summary>
        public int? PlayQueueSelectedItemID { get; set; }
        /// <summary>The playQueueSelectedItemOffset property</summary>
        public int? PlayQueueSelectedItemOffset { get; set; }
        /// <summary>The playQueueSelectedMetadataItemID property</summary>
        public int? PlayQueueSelectedMetadataItemID { get; set; }
        /// <summary>The playQueueShuffled property</summary>
        public bool? PlayQueueShuffled { get; set; }
        /// <summary>The playQueueSourceURI property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlayQueueSourceURI { get; set; }
#nullable restore
#else
        public string PlayQueueSourceURI { get; set; }
#endif
        /// <summary>The playQueueTotalCount property</summary>
        public int? PlayQueueTotalCount { get; set; }
        /// <summary>The playQueueVersion property</summary>
        public int? PlayQueueVersion { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlayQueue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlayQueue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlayQueue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "playQueueID", n => { PlayQueueID = n.GetIntValue(); } },
                { "playQueueLastAddedItemID", n => { PlayQueueLastAddedItemID = n.GetIntValue(); } },
                { "playQueueSelectedItemID", n => { PlayQueueSelectedItemID = n.GetIntValue(); } },
                { "playQueueSelectedItemOffset", n => { PlayQueueSelectedItemOffset = n.GetIntValue(); } },
                { "playQueueSelectedMetadataItemID", n => { PlayQueueSelectedMetadataItemID = n.GetIntValue(); } },
                { "playQueueShuffled", n => { PlayQueueShuffled = n.GetBoolValue(); } },
                { "playQueueSourceURI", n => { PlayQueueSourceURI = n.GetStringValue(); } },
                { "playQueueTotalCount", n => { PlayQueueTotalCount = n.GetIntValue(); } },
                { "playQueueVersion", n => { PlayQueueVersion = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteIntValue("playQueueID", PlayQueueID);
            writer.WriteIntValue("playQueueLastAddedItemID", PlayQueueLastAddedItemID);
            writer.WriteIntValue("playQueueSelectedItemID", PlayQueueSelectedItemID);
            writer.WriteIntValue("playQueueSelectedItemOffset", PlayQueueSelectedItemOffset);
            writer.WriteIntValue("playQueueSelectedMetadataItemID", PlayQueueSelectedMetadataItemID);
            writer.WriteBoolValue("playQueueShuffled", PlayQueueShuffled);
            writer.WriteStringValue("playQueueSourceURI", PlayQueueSourceURI);
            writer.WriteIntValue("playQueueTotalCount", PlayQueueTotalCount);
            writer.WriteIntValue("playQueueVersion", PlayQueueVersion);
        }
    }
}
#pragma warning restore CS0618
