// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MediaContainerWithDecision_MediaContainer_Metadata_Media_Part_Stream_decision
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "copy")]
        #pragma warning disable CS1591
        Copy,
        #pragma warning restore CS1591
        [EnumMember(Value = "transcode")]
        #pragma warning disable CS1591
        Transcode,
        #pragma warning restore CS1591
        [EnumMember(Value = "burn")]
        #pragma warning disable CS1591
        Burn,
        #pragma warning restore CS1591
        [EnumMember(Value = "unavailable")]
        #pragma warning disable CS1591
        Unavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "ignore")]
        #pragma warning disable CS1591
        Ignore,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
