// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MediaContainerWithDecision_MediaContainer_Metadata_Media_Part : global::Soenneker.Plex.OpenApiClient.Models.Part, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The decision property</summary>
        public global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision_MediaContainer_Metadata_Media_Part_decision? Decision { get; set; }
        /// <summary>The selected property</summary>
        public bool? Selected { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision_MediaContainer_Metadata_Media_Part"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision_MediaContainer_Metadata_Media_Part CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision_MediaContainer_Metadata_Media_Part();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "decision", n => { Decision = n.GetEnumValue<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision_MediaContainer_Metadata_Media_Part_decision>(); } },
                { "selected", n => { Selected = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision_MediaContainer_Metadata_Media_Part_decision>("decision", Decision);
            writer.WriteBoolValue("selected", Selected);
        }
    }
}
#pragma warning restore CS0618
