// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlexDevice_connections : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The (ip) address or domain name used for the connection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>If the connection is using IPv6</summary>
        public bool? IPv6 { get; set; }
        /// <summary>If the connection is local address</summary>
        public bool? Local { get; set; }
        /// <summary>The port used for the connection</summary>
        public int? Port { get; set; }
        /// <summary>The protocol used for the connection (http, https, etc)</summary>
        public global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections_protocol? Protocol { get; set; }
        /// <summary>If the connection is relayed through plex.direct</summary>
        public bool? Relay { get; set; }
        /// <summary>The full URI of the connection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections"/> and sets the default values.
        /// </summary>
        public PlexDevice_connections()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "IPv6", n => { IPv6 = n.GetBoolValue(); } },
                { "local", n => { Local = n.GetBoolValue(); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "protocol", n => { Protocol = n.GetEnumValue<global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections_protocol>(); } },
                { "relay", n => { Relay = n.GetBoolValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteBoolValue("IPv6", IPv6);
            writer.WriteBoolValue("local", Local);
            writer.WriteIntValue("port", Port);
            writer.WriteEnumValue<global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections_protocol>("protocol", Protocol);
            writer.WriteBoolValue("relay", Relay);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
