// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlexDevice : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accessToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The clientIdentifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientIdentifier { get; set; }
#nullable restore
#else
        public string ClientIdentifier { get; set; }
#endif
        /// <summary>The connections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections>? Connections { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections> Connections { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The device property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Device { get; set; }
#nullable restore
#else
        public string Device { get; set; }
#endif
        /// <summary>The dnsRebindingProtection property</summary>
        public bool? DnsRebindingProtection { get; set; }
        /// <summary>The home property</summary>
        public bool? Home { get; set; }
        /// <summary>The httpsRequired property</summary>
        public bool? HttpsRequired { get; set; }
        /// <summary>The lastSeenAt property</summary>
        public DateTimeOffset? LastSeenAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The natLoopbackSupported property</summary>
        public bool? NatLoopbackSupported { get; set; }
        /// <summary>The owned property</summary>
        public bool? Owned { get; set; }
        /// <summary>ownerId is null when the device is owned by the token used to send the request</summary>
        public int? OwnerId { get; set; }
        /// <summary>The platform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Platform { get; set; }
#nullable restore
#else
        public string Platform { get; set; }
#endif
        /// <summary>The platformVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlatformVersion { get; set; }
#nullable restore
#else
        public string PlatformVersion { get; set; }
#endif
        /// <summary>The presence property</summary>
        public bool? Presence { get; set; }
        /// <summary>The product property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Product { get; set; }
#nullable restore
#else
        public string Product { get; set; }
#endif
        /// <summary>The productVersion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductVersion { get; set; }
#nullable restore
#else
        public string ProductVersion { get; set; }
#endif
        /// <summary>The provides property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provides { get; set; }
#nullable restore
#else
        public string Provides { get; set; }
#endif
        /// <summary>The publicAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicAddress { get; set; }
#nullable restore
#else
        public string PublicAddress { get; set; }
#endif
        /// <summary>The publicAddressMatches property</summary>
        public bool? PublicAddressMatches { get; set; }
        /// <summary>The relay property</summary>
        public bool? Relay { get; set; }
        /// <summary>The sourceTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceTitle { get; set; }
#nullable restore
#else
        public string SourceTitle { get; set; }
#endif
        /// <summary>The synced property</summary>
        public bool? Synced { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Models.PlexDevice"/> and sets the default values.
        /// </summary>
        public PlexDevice()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.PlexDevice"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Models.PlexDevice CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.PlexDevice();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessToken", n => { AccessToken = n.GetStringValue(); } },
                { "clientIdentifier", n => { ClientIdentifier = n.GetStringValue(); } },
                { "connections", n => { Connections = n.GetCollectionOfObjectValues<global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections>(global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "device", n => { Device = n.GetStringValue(); } },
                { "dnsRebindingProtection", n => { DnsRebindingProtection = n.GetBoolValue(); } },
                { "home", n => { Home = n.GetBoolValue(); } },
                { "httpsRequired", n => { HttpsRequired = n.GetBoolValue(); } },
                { "lastSeenAt", n => { LastSeenAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "natLoopbackSupported", n => { NatLoopbackSupported = n.GetBoolValue(); } },
                { "owned", n => { Owned = n.GetBoolValue(); } },
                { "ownerId", n => { OwnerId = n.GetIntValue(); } },
                { "platform", n => { Platform = n.GetStringValue(); } },
                { "platformVersion", n => { PlatformVersion = n.GetStringValue(); } },
                { "presence", n => { Presence = n.GetBoolValue(); } },
                { "product", n => { Product = n.GetStringValue(); } },
                { "productVersion", n => { ProductVersion = n.GetStringValue(); } },
                { "provides", n => { Provides = n.GetStringValue(); } },
                { "publicAddress", n => { PublicAddress = n.GetStringValue(); } },
                { "publicAddressMatches", n => { PublicAddressMatches = n.GetBoolValue(); } },
                { "relay", n => { Relay = n.GetBoolValue(); } },
                { "sourceTitle", n => { SourceTitle = n.GetStringValue(); } },
                { "synced", n => { Synced = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessToken", AccessToken);
            writer.WriteStringValue("clientIdentifier", ClientIdentifier);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plex.OpenApiClient.Models.PlexDevice_connections>("connections", Connections);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("device", Device);
            writer.WriteBoolValue("dnsRebindingProtection", DnsRebindingProtection);
            writer.WriteBoolValue("home", Home);
            writer.WriteBoolValue("httpsRequired", HttpsRequired);
            writer.WriteDateTimeOffsetValue("lastSeenAt", LastSeenAt);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("natLoopbackSupported", NatLoopbackSupported);
            writer.WriteBoolValue("owned", Owned);
            writer.WriteIntValue("ownerId", OwnerId);
            writer.WriteStringValue("platform", Platform);
            writer.WriteStringValue("platformVersion", PlatformVersion);
            writer.WriteBoolValue("presence", Presence);
            writer.WriteStringValue("product", Product);
            writer.WriteStringValue("productVersion", ProductVersion);
            writer.WriteStringValue("provides", Provides);
            writer.WriteStringValue("publicAddress", PublicAddress);
            writer.WriteBoolValue("publicAddressMatches", PublicAddressMatches);
            writer.WriteBoolValue("relay", Relay);
            writer.WriteStringValue("sourceTitle", SourceTitle);
            writer.WriteBoolValue("synced", Synced);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
