// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    /// <summary>
    /// `Stream` represents a particular stream from a media item, such as the video stream, audio stream, or subtitle stream. The stream may either be part of the file represented by the parent `Part` or, especially for subtitles, an external file. The stream contains more detailed information about the specific stream. For example, a video may include the `aspectRatio` at the `Media` level, but detailed information about the video stream like the color space will be included on the `Stream` for the video stream.  Note that photos do not have streams (mostly as an optimization).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StreamObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ReplayGain album gain in dB.</summary>
        public double? AlbumGain { get; set; }
        /// <summary>ReplayGain album peak amplitude.</summary>
        public double? AlbumPeak { get; set; }
        /// <summary>ReplayGain album dynamic range in dB.</summary>
        public double? AlbumRange { get; set; }
        /// <summary>Audio channel layout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudioChannelLayout { get; set; }
#nullable restore
#else
        public string AudioChannelLayout { get; set; }
#endif
        /// <summary>Bit depth of the video stream.</summary>
        public int? BitDepth { get; set; }
        /// <summary>Bitrate of the stream.</summary>
        public int? Bitrate { get; set; }
        /// <summary>Audio bitrate mode (cbr or vbr).</summary>
        public global::Soenneker.Plex.OpenApiClient.Models.Stream_bitrateMode? BitrateMode { get; set; }
        /// <summary>Indicates if the stream can auto-sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync? CanAutoSync { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync CanAutoSync { get; set; }
#endif
        /// <summary>Number of audio channels (for audio streams).</summary>
        public int? Channels { get; set; }
        /// <summary>Chroma sample location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChromaLocation { get; set; }
#nullable restore
#else
        public string ChromaLocation { get; set; }
#endif
        /// <summary>Chroma subsampling format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChromaSubsampling { get; set; }
#nullable restore
#else
        public string ChromaSubsampling { get; set; }
#endif
        /// <summary>The closedCaptions property</summary>
        public bool? ClosedCaptions { get; set; }
        /// <summary>Codec used by the stream.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Codec { get; set; }
#nullable restore
#else
        public string Codec { get; set; }
#endif
        /// <summary>Coded video height.</summary>
        public int? CodedHeight { get; set; }
        /// <summary>Coded video width.</summary>
        public int? CodedWidth { get; set; }
        /// <summary>Color primaries used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorPrimaries { get; set; }
#nullable restore
#else
        public string ColorPrimaries { get; set; }
#endif
        /// <summary>Color range (e.g., tv).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorRange { get; set; }
#nullable restore
#else
        public string ColorRange { get; set; }
#endif
        /// <summary>Color space.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorSpace { get; set; }
#nullable restore
#else
        public string ColorSpace { get; set; }
#endif
        /// <summary>Color transfer characteristics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorTrc { get; set; }
#nullable restore
#else
        public string ColorTrc { get; set; }
#endif
        /// <summary>Indicates if this stream is default.</summary>
        public bool? Default { get; set; }
        /// <summary>Display title for the stream.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayTitle { get; set; }
#nullable restore
#else
        public string DisplayTitle { get; set; }
#endif
        /// <summary>Dolby Vision BL compatibility ID.</summary>
        public int? DOVIBLCompatID { get; set; }
        /// <summary>Indicates if Dolby Vision BL is present.</summary>
        public bool? DOVIBLPresent { get; set; }
        /// <summary>Indicates if Dolby Vision EL is present.</summary>
        public bool? DOVIELPresent { get; set; }
        /// <summary>Dolby Vision level.</summary>
        public int? DOVILevel { get; set; }
        /// <summary>Indicates if Dolby Vision is present.</summary>
        public bool? DOVIPresent { get; set; }
        /// <summary>Dolby Vision profile.</summary>
        public int? DOVIProfile { get; set; }
        /// <summary>Indicates if Dolby Vision RPU is present.</summary>
        public bool? DOVIRPUPresent { get; set; }
        /// <summary>Dolby Vision version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DOVIVersion { get; set; }
#nullable restore
#else
        public string DOVIVersion { get; set; }
#endif
        /// <summary>Indicates if the stream is a dub.</summary>
        public bool? Dub { get; set; }
        /// <summary>The embeddedInVideo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmbeddedInVideo { get; set; }
#nullable restore
#else
        public string EmbeddedInVideo { get; set; }
#endif
        /// <summary>Loudness ramp end type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndRamp { get; set; }
#nullable restore
#else
        public string EndRamp { get; set; }
#endif
        /// <summary>Extended display title for the stream.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtendedDisplayTitle { get; set; }
#nullable restore
#else
        public string ExtendedDisplayTitle { get; set; }
#endif
        /// <summary>The forced property</summary>
        public bool? Forced { get; set; }
        /// <summary>Format of the stream (e.g., srt).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>Frame rate of the stream.</summary>
        public float? FrameRate { get; set; }
        /// <summary>Track replay gain in dB.</summary>
        public double? Gain { get; set; }
        /// <summary>The hasScalingMatrix property</summary>
        public bool? HasScalingMatrix { get; set; }
        /// <summary>Indicates whether header compression is enabled.</summary>
        public bool? HeaderCompression { get; set; }
        /// <summary>Indicates if the stream is for the hearing impaired.</summary>
        public bool? HearingImpaired { get; set; }
        /// <summary>Height of the video stream.</summary>
        public int? Height { get; set; }
        /// <summary>Unique stream identifier.</summary>
        public int? Id { get; set; }
        /// <summary>Index of the stream.</summary>
        public int? Index { get; set; }
        /// <summary>Key to access this stream part.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>Language of the stream.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>ISO language code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LanguageCode { get; set; }
#nullable restore
#else
        public string LanguageCode { get; set; }
#endif
        /// <summary>Language tag (e.g., en).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LanguageTag { get; set; }
#nullable restore
#else
        public string LanguageTag { get; set; }
#endif
        /// <summary>Video level.</summary>
        public int? Level { get; set; }
        /// <summary>Integrated loudness in LUFS.</summary>
        public double? Loudness { get; set; }
        /// <summary>Loudness range in LU.</summary>
        public double? Lra { get; set; }
        /// <summary>Minimum lines in the lyric file.</summary>
        public int? MinLines { get; set; }
        /// <summary>Indicates if this is the original stream.</summary>
        public bool? Original { get; set; }
        /// <summary>Track peak amplitude.</summary>
        public double? Peak { get; set; }
        /// <summary>Whether the subtitle is an exact match.</summary>
        public bool? PerfectMatch { get; set; }
        /// <summary>Video profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profile { get; set; }
#nullable restore
#else
        public string Profile { get; set; }
#endif
        /// <summary>Lyric or subtitle provider name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provider { get; set; }
#nullable restore
#else
        public string Provider { get; set; }
#endif
        /// <summary>Subtitle provider display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderTitle { get; set; }
#nullable restore
#else
        public string ProviderTitle { get; set; }
#endif
        /// <summary>Number of reference frames.</summary>
        public int? RefFrames { get; set; }
        /// <summary>Sampling rate for the audio stream.</summary>
        public int? SamplingRate { get; set; }
        /// <summary>The scanType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScanType { get; set; }
#nullable restore
#else
        public string ScanType { get; set; }
#endif
        /// <summary>Subtitle match confidence score (0-100).</summary>
        public double? Score { get; set; }
        /// <summary>Indicates if this stream is selected (applicable for audio streams).</summary>
        public bool? Selected { get; set; }
        /// <summary>Source identifier for the subtitle.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceKey { get; set; }
#nullable restore
#else
        public string SourceKey { get; set; }
#endif
        /// <summary>Loudness ramp start type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartRamp { get; set; }
#nullable restore
#else
        public string StartRamp { get; set; }
#endif
        /// <summary>The streamIdentifier property</summary>
        public int? StreamIdentifier { get; set; }
        /// <summary>The streamType property</summary>
        public int? StreamType { get; set; }
        /// <summary>Whether lyrics are timestamped.</summary>
        public bool? Timed { get; set; }
        /// <summary>Optional title for the stream (e.g., language variant).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Whether the subtitle is temporary or downloaded.</summary>
        public bool? Transient { get; set; }
        /// <summary>ID of the user who added the subtitle.</summary>
        public int? UserID { get; set; }
        /// <summary>Whether this audio track is an audio description track.</summary>
        public bool? VisualImpaired { get; set; }
        /// <summary>Width of the video stream.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Models.StreamObject"/> and sets the default values.
        /// </summary>
        public StreamObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.StreamObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Models.StreamObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.StreamObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albumGain", n => { AlbumGain = n.GetDoubleValue(); } },
                { "albumPeak", n => { AlbumPeak = n.GetDoubleValue(); } },
                { "albumRange", n => { AlbumRange = n.GetDoubleValue(); } },
                { "audioChannelLayout", n => { AudioChannelLayout = n.GetStringValue(); } },
                { "bitDepth", n => { BitDepth = n.GetIntValue(); } },
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "bitrateMode", n => { BitrateMode = n.GetEnumValue<global::Soenneker.Plex.OpenApiClient.Models.Stream_bitrateMode>(); } },
                { "canAutoSync", n => { CanAutoSync = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync>(global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync.CreateFromDiscriminatorValue); } },
                { "channels", n => { Channels = n.GetIntValue(); } },
                { "chromaLocation", n => { ChromaLocation = n.GetStringValue(); } },
                { "chromaSubsampling", n => { ChromaSubsampling = n.GetStringValue(); } },
                { "closedCaptions", n => { ClosedCaptions = n.GetBoolValue(); } },
                { "codec", n => { Codec = n.GetStringValue(); } },
                { "codedHeight", n => { CodedHeight = n.GetIntValue(); } },
                { "codedWidth", n => { CodedWidth = n.GetIntValue(); } },
                { "colorPrimaries", n => { ColorPrimaries = n.GetStringValue(); } },
                { "colorRange", n => { ColorRange = n.GetStringValue(); } },
                { "colorSpace", n => { ColorSpace = n.GetStringValue(); } },
                { "colorTrc", n => { ColorTrc = n.GetStringValue(); } },
                { "DOVIBLCompatID", n => { DOVIBLCompatID = n.GetIntValue(); } },
                { "DOVIBLPresent", n => { DOVIBLPresent = n.GetBoolValue(); } },
                { "DOVIELPresent", n => { DOVIELPresent = n.GetBoolValue(); } },
                { "DOVILevel", n => { DOVILevel = n.GetIntValue(); } },
                { "DOVIPresent", n => { DOVIPresent = n.GetBoolValue(); } },
                { "DOVIProfile", n => { DOVIProfile = n.GetIntValue(); } },
                { "DOVIRPUPresent", n => { DOVIRPUPresent = n.GetBoolValue(); } },
                { "DOVIVersion", n => { DOVIVersion = n.GetStringValue(); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "displayTitle", n => { DisplayTitle = n.GetStringValue(); } },
                { "dub", n => { Dub = n.GetBoolValue(); } },
                { "embeddedInVideo", n => { EmbeddedInVideo = n.GetStringValue(); } },
                { "endRamp", n => { EndRamp = n.GetStringValue(); } },
                { "extendedDisplayTitle", n => { ExtendedDisplayTitle = n.GetStringValue(); } },
                { "forced", n => { Forced = n.GetBoolValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "frameRate", n => { FrameRate = n.GetFloatValue(); } },
                { "gain", n => { Gain = n.GetDoubleValue(); } },
                { "hasScalingMatrix", n => { HasScalingMatrix = n.GetBoolValue(); } },
                { "headerCompression", n => { HeaderCompression = n.GetBoolValue(); } },
                { "hearingImpaired", n => { HearingImpaired = n.GetBoolValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "languageCode", n => { LanguageCode = n.GetStringValue(); } },
                { "languageTag", n => { LanguageTag = n.GetStringValue(); } },
                { "level", n => { Level = n.GetIntValue(); } },
                { "loudness", n => { Loudness = n.GetDoubleValue(); } },
                { "lra", n => { Lra = n.GetDoubleValue(); } },
                { "minLines", n => { MinLines = n.GetIntValue(); } },
                { "original", n => { Original = n.GetBoolValue(); } },
                { "peak", n => { Peak = n.GetDoubleValue(); } },
                { "perfectMatch", n => { PerfectMatch = n.GetBoolValue(); } },
                { "profile", n => { Profile = n.GetStringValue(); } },
                { "provider", n => { Provider = n.GetStringValue(); } },
                { "providerTitle", n => { ProviderTitle = n.GetStringValue(); } },
                { "refFrames", n => { RefFrames = n.GetIntValue(); } },
                { "samplingRate", n => { SamplingRate = n.GetIntValue(); } },
                { "scanType", n => { ScanType = n.GetStringValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "selected", n => { Selected = n.GetBoolValue(); } },
                { "sourceKey", n => { SourceKey = n.GetStringValue(); } },
                { "startRamp", n => { StartRamp = n.GetStringValue(); } },
                { "streamIdentifier", n => { StreamIdentifier = n.GetIntValue(); } },
                { "streamType", n => { StreamType = n.GetIntValue(); } },
                { "timed", n => { Timed = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "transient", n => { Transient = n.GetBoolValue(); } },
                { "userID", n => { UserID = n.GetIntValue(); } },
                { "visualImpaired", n => { VisualImpaired = n.GetBoolValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("albumGain", AlbumGain);
            writer.WriteDoubleValue("albumPeak", AlbumPeak);
            writer.WriteDoubleValue("albumRange", AlbumRange);
            writer.WriteStringValue("audioChannelLayout", AudioChannelLayout);
            writer.WriteIntValue("bitDepth", BitDepth);
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteEnumValue<global::Soenneker.Plex.OpenApiClient.Models.Stream_bitrateMode>("bitrateMode", BitrateMode);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync>("canAutoSync", CanAutoSync);
            writer.WriteIntValue("channels", Channels);
            writer.WriteStringValue("chromaLocation", ChromaLocation);
            writer.WriteStringValue("chromaSubsampling", ChromaSubsampling);
            writer.WriteBoolValue("closedCaptions", ClosedCaptions);
            writer.WriteStringValue("codec", Codec);
            writer.WriteIntValue("codedHeight", CodedHeight);
            writer.WriteIntValue("codedWidth", CodedWidth);
            writer.WriteStringValue("colorPrimaries", ColorPrimaries);
            writer.WriteStringValue("colorRange", ColorRange);
            writer.WriteStringValue("colorSpace", ColorSpace);
            writer.WriteStringValue("colorTrc", ColorTrc);
            writer.WriteBoolValue("default", Default);
            writer.WriteStringValue("displayTitle", DisplayTitle);
            writer.WriteIntValue("DOVIBLCompatID", DOVIBLCompatID);
            writer.WriteBoolValue("DOVIBLPresent", DOVIBLPresent);
            writer.WriteBoolValue("DOVIELPresent", DOVIELPresent);
            writer.WriteIntValue("DOVILevel", DOVILevel);
            writer.WriteBoolValue("DOVIPresent", DOVIPresent);
            writer.WriteIntValue("DOVIProfile", DOVIProfile);
            writer.WriteBoolValue("DOVIRPUPresent", DOVIRPUPresent);
            writer.WriteStringValue("DOVIVersion", DOVIVersion);
            writer.WriteBoolValue("dub", Dub);
            writer.WriteStringValue("embeddedInVideo", EmbeddedInVideo);
            writer.WriteStringValue("endRamp", EndRamp);
            writer.WriteStringValue("extendedDisplayTitle", ExtendedDisplayTitle);
            writer.WriteBoolValue("forced", Forced);
            writer.WriteStringValue("format", Format);
            writer.WriteFloatValue("frameRate", FrameRate);
            writer.WriteDoubleValue("gain", Gain);
            writer.WriteBoolValue("hasScalingMatrix", HasScalingMatrix);
            writer.WriteBoolValue("headerCompression", HeaderCompression);
            writer.WriteBoolValue("hearingImpaired", HearingImpaired);
            writer.WriteIntValue("height", Height);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("index", Index);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("language", Language);
            writer.WriteStringValue("languageCode", LanguageCode);
            writer.WriteStringValue("languageTag", LanguageTag);
            writer.WriteIntValue("level", Level);
            writer.WriteDoubleValue("loudness", Loudness);
            writer.WriteDoubleValue("lra", Lra);
            writer.WriteIntValue("minLines", MinLines);
            writer.WriteBoolValue("original", Original);
            writer.WriteDoubleValue("peak", Peak);
            writer.WriteBoolValue("perfectMatch", PerfectMatch);
            writer.WriteStringValue("profile", Profile);
            writer.WriteStringValue("provider", Provider);
            writer.WriteStringValue("providerTitle", ProviderTitle);
            writer.WriteIntValue("refFrames", RefFrames);
            writer.WriteIntValue("samplingRate", SamplingRate);
            writer.WriteStringValue("scanType", ScanType);
            writer.WriteDoubleValue("score", Score);
            writer.WriteBoolValue("selected", Selected);
            writer.WriteStringValue("sourceKey", SourceKey);
            writer.WriteStringValue("startRamp", StartRamp);
            writer.WriteIntValue("streamIdentifier", StreamIdentifier);
            writer.WriteIntValue("streamType", StreamType);
            writer.WriteBoolValue("timed", Timed);
            writer.WriteStringValue("title", Title);
            writer.WriteBoolValue("transient", Transient);
            writer.WriteIntValue("userID", UserID);
            writer.WriteBoolValue("visualImpaired", VisualImpaired);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Stream_canAutoSync : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Plex.OpenApiClient.Models.StreamObject.Stream_canAutoSync();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
