// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TranscodeJob_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "transcode")]
        #pragma warning disable CS1591
        Transcode,
        #pragma warning restore CS1591
    }
}
