// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    /// <summary>
    /// Status of the PMS updater.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdaterStatus : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp of the last update check.</summary>
        public int? CheckedAt { get; set; }
        /// <summary>The URL where the update is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DownloadURL { get; set; }
#nullable restore
#else
        public string DownloadURL { get; set; }
#endif
        /// <summary>The Release property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plex.OpenApiClient.Models.Release>? Release { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plex.OpenApiClient.Models.Release> Release { get; set; }
#endif
        /// <summary>The current error code (0 means no error).</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Models.UpdaterStatus"/> and sets the default values.
        /// </summary>
        public UpdaterStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.UpdaterStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Models.UpdaterStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.UpdaterStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checkedAt", n => { CheckedAt = n.GetIntValue(); } },
                { "downloadURL", n => { DownloadURL = n.GetStringValue(); } },
                { "Release", n => { Release = n.GetCollectionOfObjectValues<global::Soenneker.Plex.OpenApiClient.Models.Release>(global::Soenneker.Plex.OpenApiClient.Models.Release.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("checkedAt", CheckedAt);
            writer.WriteStringValue("downloadURL", DownloadURL);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plex.OpenApiClient.Models.Release>("Release", Release);
            writer.WriteIntValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
