// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    /// <summary>String representation of subscriptionActive</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserPlexAccount_subscription_status
    {
        [EnumMember(Value = "Inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "Active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
    }
}
