// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserProfile : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If the account has automatically select audio and subtitle tracks enabled</summary>
        public bool? AutoSelectAudio { get; set; }
        /// <summary>The autoSelectSubtitle property</summary>
        public int? AutoSelectSubtitle { get; set; }
        /// <summary>The defaultAudioAccessibility property</summary>
        public int? DefaultAudioAccessibility { get; set; }
        /// <summary>The preferred audio language for the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultAudioLanguage { get; set; }
#nullable restore
#else
        public string DefaultAudioLanguage { get; set; }
#endif
        /// <summary>The preferred audio languages for the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DefaultAudioLanguages { get; set; }
#nullable restore
#else
        public List<string> DefaultAudioLanguages { get; set; }
#endif
        /// <summary>The defaultSubtitleAccessibility property</summary>
        public int? DefaultSubtitleAccessibility { get; set; }
        /// <summary>The defaultSubtitleForced property</summary>
        public int? DefaultSubtitleForced { get; set; }
        /// <summary>The preferred subtitle language for the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSubtitleLanguage { get; set; }
#nullable restore
#else
        public string DefaultSubtitleLanguage { get; set; }
#endif
        /// <summary>The preferred subtitle languages for the account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DefaultSubtitleLanguages { get; set; }
#nullable restore
#else
        public List<string> DefaultSubtitleLanguages { get; set; }
#endif
        /// <summary>The languages for media reviews visibility</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MediaReviewsLanguages { get; set; }
#nullable restore
#else
        public List<string> MediaReviewsLanguages { get; set; }
#endif
        /// <summary>The mediaReviewsVisibility property</summary>
        public int? MediaReviewsVisibility { get; set; }
        /// <summary>The watchedIndicator property</summary>
        public int? WatchedIndicator { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Models.UserProfile"/> and sets the default values.
        /// </summary>
        public UserProfile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.UserProfile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Models.UserProfile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.UserProfile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoSelectAudio", n => { AutoSelectAudio = n.GetBoolValue(); } },
                { "autoSelectSubtitle", n => { AutoSelectSubtitle = n.GetIntValue(); } },
                { "defaultAudioAccessibility", n => { DefaultAudioAccessibility = n.GetIntValue(); } },
                { "defaultAudioLanguage", n => { DefaultAudioLanguage = n.GetStringValue(); } },
                { "defaultAudioLanguages", n => { DefaultAudioLanguages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "defaultSubtitleAccessibility", n => { DefaultSubtitleAccessibility = n.GetIntValue(); } },
                { "defaultSubtitleForced", n => { DefaultSubtitleForced = n.GetIntValue(); } },
                { "defaultSubtitleLanguage", n => { DefaultSubtitleLanguage = n.GetStringValue(); } },
                { "defaultSubtitleLanguages", n => { DefaultSubtitleLanguages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "mediaReviewsLanguages", n => { MediaReviewsLanguages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "mediaReviewsVisibility", n => { MediaReviewsVisibility = n.GetIntValue(); } },
                { "watchedIndicator", n => { WatchedIndicator = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoSelectAudio", AutoSelectAudio);
            writer.WriteIntValue("autoSelectSubtitle", AutoSelectSubtitle);
            writer.WriteIntValue("defaultAudioAccessibility", DefaultAudioAccessibility);
            writer.WriteStringValue("defaultAudioLanguage", DefaultAudioLanguage);
            writer.WriteCollectionOfPrimitiveValues<string>("defaultAudioLanguages", DefaultAudioLanguages);
            writer.WriteIntValue("defaultSubtitleAccessibility", DefaultSubtitleAccessibility);
            writer.WriteIntValue("defaultSubtitleForced", DefaultSubtitleForced);
            writer.WriteStringValue("defaultSubtitleLanguage", DefaultSubtitleLanguage);
            writer.WriteCollectionOfPrimitiveValues<string>("defaultSubtitleLanguages", DefaultSubtitleLanguages);
            writer.WriteCollectionOfPrimitiveValues<string>("mediaReviewsLanguages", MediaReviewsLanguages);
            writer.WriteIntValue("mediaReviewsVisibility", MediaReviewsVisibility);
            writer.WriteIntValue("watchedIndicator", WatchedIndicator);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
