// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Models
{
    /// <summary>
    /// Payload delivered by Plex to configured webhook URLs.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookPayload : IAdditionalDataHolder, IParsable
    {
        /// <summary>The Account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Account? Account { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Account Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Event type that triggered the webhook.</summary>
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_event? Event { get; set; }
        /// <summary>The media item associated with the event. Shape varies by event type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Metadata Metadata { get; set; }
#endif
        /// <summary>The owner property</summary>
        public bool? Owner { get; set; }
        /// <summary>The Player property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Player? Player { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Player Player { get; set; }
#endif
        /// <summary>The Server property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Server? Server { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Server Server { get; set; }
#endif
        /// <summary>The user property</summary>
        public bool? User { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload"/> and sets the default values.
        /// </summary>
        public WebhookPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Account", n => { Account = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Account>(global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Account.CreateFromDiscriminatorValue); } },
                { "event", n => { Event = n.GetEnumValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_event>(); } },
                { "Metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Metadata>(global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Metadata.CreateFromDiscriminatorValue); } },
                { "owner", n => { Owner = n.GetBoolValue(); } },
                { "Player", n => { Player = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Player>(global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Player.CreateFromDiscriminatorValue); } },
                { "Server", n => { Server = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Server>(global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Server.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Account>("Account", Account);
            writer.WriteEnumValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_event>("event", Event);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Metadata>("Metadata", Metadata);
            writer.WriteBoolValue("owner", Owner);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Player>("Player", Player);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.WebhookPayload_Server>("Server", Server);
            writer.WriteBoolValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
