// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.DownloadQueue.Item
{
    /// <summary>The state of this queue  - deciding: At least one item is still being decided  - waiting: At least one item is waiting for transcode and none are currently transcoding  - processing: At least one item is being transcoded  - done: All items are available (or potentially expired)  - error: At least one item has encountered an error</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithQueueGetResponse_MediaContainer_DownloadQueue_status
    {
        [EnumMember(Value = "deciding")]
        #pragma warning disable CS1591
        Deciding,
        #pragma warning restore CS1591
        [EnumMember(Value = "waiting")]
        #pragma warning disable CS1591
        Waiting,
        #pragma warning restore CS1591
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "done")]
        #pragma warning disable CS1591
        Done,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
