// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Plex.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Media.Subscriptions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubscriptionsPostResponse_MediaContainer : global::Soenneker.Plex.OpenApiClient.Models.MediaContainer, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The MediaSubscription property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Plex.OpenApiClient.Models.MediaSubscription>? MediaSubscription { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Plex.OpenApiClient.Models.MediaSubscription> MediaSubscription { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Media.Subscriptions.SubscriptionsPostResponse_MediaContainer"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Plex.OpenApiClient.Media.Subscriptions.SubscriptionsPostResponse_MediaContainer CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Media.Subscriptions.SubscriptionsPostResponse_MediaContainer();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "MediaSubscription", n => { MediaSubscription = n.GetCollectionOfObjectValues<global::Soenneker.Plex.OpenApiClient.Models.MediaSubscription>(global::Soenneker.Plex.OpenApiClient.Models.MediaSubscription.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Plex.OpenApiClient.Models.MediaSubscription>("MediaSubscription", MediaSubscription);
        }
    }
}
#pragma warning restore CS0618
