// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors
{
    [Obsolete("This class is obsolete. Use ColorsGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ColorsResponse : global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors.ColorsGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors.ColorsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors.ColorsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Colors.ColorsResponse();
        }
    }
}
#pragma warning restore CS0618
