// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.DownloadQueue.Item.Items
{
    /// <summary>The state of the item:  - deciding: The item decision is pending  - waiting: The item is waiting for transcode  - processing: The item is being transcoded  - available: The item is available for download  - error: The item encountered an error in the decision or transcode  - expired: The transcoded item has timed out and is no longer available</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemsGetResponse_MediaContainer_DownloadQueueItem_status
    {
        [EnumMember(Value = "deciding")]
        #pragma warning disable CS1591
        Deciding,
        #pragma warning restore CS1591
        [EnumMember(Value = "waiting")]
        #pragma warning disable CS1591
        Waiting,
        #pragma warning restore CS1591
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
    }
}
