// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision
{
    /// <summary>
    /// Builds and executes requests for operations under \{transcodeType}\:\transcode\universal\decision
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DecisionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DecisionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{transcodeType}/:/transcode/universal/decision{?advancedSubtitles*,audioBoost*,audioChannelCount*,autoAdjustQuality*,autoAdjustSubtitle*,directPlay*,directStream*,directStreamAudio*,disableResolutionRotation*,hasMDE*,location*,mediaBufferSize*,mediaIndex*,musicBitrate*,offset*,partIndex*,path*,peakBitrate*,photoResolution*,protocol*,secondsPerSegment*,subtitleSize*,subtitles*,transcodeSessionId*,videoBitrate*,videoQuality*,videoResolution*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DecisionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{transcodeType}/:/transcode/universal/decision{?advancedSubtitles*,audioBoost*,audioChannelCount*,autoAdjustQuality*,autoAdjustSubtitle*,directPlay*,directStream*,directStreamAudio*,disableResolutionRotation*,hasMDE*,location*,mediaBufferSize*,mediaIndex*,musicBitrate*,offset*,partIndex*,path*,peakBitrate*,photoResolution*,protocol*,secondsPerSegment*,subtitleSize*,subtitles*,transcodeSessionId*,videoBitrate*,videoQuality*,videoResolution*}", rawUrl)
        {
        }
        /// <summary>
        /// Make a decision on media playback based on client profile, and requested settings such as bandwidth and resolution.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision?> GetAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder.DecisionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision> GetAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder.DecisionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision>(requestInfo, global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithDecision.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Make a decision on media playback based on client profile, and requested settings such as bandwidth and resolution.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder.DecisionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder.DecisionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.DecisionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Make a decision on media playback based on client profile, and requested settings such as bandwidth and resolution.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DecisionRequestBuilderGetQueryParameters 
        {
            /// <summary>Indicates how incompatible advanced subtitles (such as ass/ssa) should be included: * &apos;burn&apos; - Burn incompatible advanced text subtitles into the video stream * &apos;text&apos; - Transcode incompatible advanced text subtitles to a compatible text format, even if some markup is lost</summary>
            [QueryParameter("advancedSubtitles")]
            public global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.GetAdvancedSubtitlesQueryParameterType? AdvancedSubtitles { get; set; }
            /// <summary>Percentage of original audio loudness to use when transcoding (100 is equivalent to original volume, 50 is half, 200 is double, etc)</summary>
            [QueryParameter("audioBoost")]
            public int? AudioBoost { get; set; }
            /// <summary>Target video number of audio channels.</summary>
            [QueryParameter("audioChannelCount")]
            public int? AudioChannelCount { get; set; }
            /// <summary>Indicates the client supports ABR.</summary>
            [QueryParameter("autoAdjustQuality")]
            public int? AutoAdjustQuality { get; set; }
            /// <summary>Indicates if the server should adjust subtitles based on Voice Activity Data.</summary>
            [QueryParameter("autoAdjustSubtitle")]
            public int? AutoAdjustSubtitle { get; set; }
            /// <summary>Indicates the client supports direct playing the indicated content.</summary>
            [QueryParameter("directPlay")]
            public int? DirectPlay { get; set; }
            /// <summary>Indicates the client supports direct streaming the video of the indicated content.</summary>
            [QueryParameter("directStream")]
            public int? DirectStream { get; set; }
            /// <summary>Indicates the client supports direct streaming the audio of the indicated content.</summary>
            [QueryParameter("directStreamAudio")]
            public int? DirectStreamAudio { get; set; }
            /// <summary>Indicates if resolution should be adjusted for orientation.</summary>
            [QueryParameter("disableResolutionRotation")]
            public int? DisableResolutionRotation { get; set; }
            /// <summary>Ignore client profiles when determining if direct play is possible. Only has an effect when directPlay=1 and both mediaIndex and partIndex are specified and neither are -1</summary>
            [QueryParameter("hasMDE")]
            public int? HasMDE { get; set; }
            /// <summary>Network type of the client, can be used to help determine target bitrate.</summary>
            [QueryParameter("location")]
            public global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.GetLocationQueryParameterType? Location { get; set; }
            /// <summary>Buffer size used in playback (in KB). Clients should specify a lower bound if not known exactly. This value could make the difference between transcoding and direct play on bandwidth constrained networks.</summary>
            [QueryParameter("mediaBufferSize")]
            public int? MediaBufferSize { get; set; }
            /// <summary>Index of the media to transcode. -1 or not specified indicates let the server choose.</summary>
            [QueryParameter("mediaIndex")]
            public int? MediaIndex { get; set; }
            /// <summary>Target bitrate for audio only files (in kbps, used to transcode).</summary>
            [QueryParameter("musicBitrate")]
            public int? MusicBitrate { get; set; }
            /// <summary>Offset from the start of the media (in seconds).</summary>
            [QueryParameter("offset")]
            public double? Offset { get; set; }
            /// <summary>Index of the part to transcode. -1 or not specified indicates the server should join parts together in a transcode</summary>
            [QueryParameter("partIndex")]
            public int? PartIndex { get; set; }
            /// <summary>Internal PMS path of the media to transcode.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("path")]
            public string? Path { get; set; }
#nullable restore
#else
            [QueryParameter("path")]
            public string Path { get; set; }
#endif
            /// <summary>Maximum bitrate (in kbps) to use in ABR.</summary>
            [QueryParameter("peakBitrate")]
            public int? PeakBitrate { get; set; }
            /// <summary>Target photo resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("photoResolution")]
            public string? PhotoResolution { get; set; }
#nullable restore
#else
            [QueryParameter("photoResolution")]
            public string PhotoResolution { get; set; }
#endif
            /// <summary>Indicates the network streaming protocol to be used for the transcode session: * &apos;http&apos; - include the file in the http response such as MKV streaming * &apos;hls&apos; - hls stream (RFC 8216) * &apos;dash&apos; - dash stream (ISO/IEC 23009-1:2022)</summary>
            [QueryParameter("protocol")]
            public global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.GetProtocolQueryParameterType? Protocol { get; set; }
            /// <summary>Number of seconds to include in each transcoded segment</summary>
            [QueryParameter("secondsPerSegment")]
            public int? SecondsPerSegment { get; set; }
            /// <summary>Indicates how subtitles should be included: * &apos;auto&apos; - Compute the appropriate subtitle setting automatically * &apos;burn&apos; - Burn the selected subtitle; auto if no selected subtitle * &apos;none&apos; - Ignore all subtitle streams * &apos;sidecar&apos; - The selected subtitle should be provided as a sidecar * &apos;embedded&apos; - The selected subtitle should be provided as an embedded stream * &apos;segmented&apos; - The selected subtitle should be provided as a segmented stream</summary>
            [QueryParameter("subtitles")]
            public global::Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Decision.GetSubtitlesQueryParameterType? Subtitles { get; set; }
            /// <summary>Percentage of original subtitle size to use when burning subtitles (100 is equivalent to original size, 50 is half, ect)</summary>
            [QueryParameter("subtitleSize")]
            public int? SubtitleSize { get; set; }
            /// <summary>Transcode session UUID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("transcodeSessionId")]
            public string? TranscodeSessionId { get; set; }
#nullable restore
#else
            [QueryParameter("transcodeSessionId")]
            public string TranscodeSessionId { get; set; }
#endif
            /// <summary>Target video bitrate (in kbps).</summary>
            [QueryParameter("videoBitrate")]
            public int? VideoBitrate { get; set; }
            /// <summary>Target photo quality.</summary>
            [QueryParameter("videoQuality")]
            public int? VideoQuality { get; set; }
            /// <summary>Target maximum video resolution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("videoResolution")]
            public string? VideoResolution { get; set; }
#nullable restore
#else
            [QueryParameter("videoResolution")]
            public string VideoResolution { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
