// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Status.Sessions.History.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithHistoryGetResponse_MediaContainer_Metadata : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account id of this playback</summary>
        public int? AccountID { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The device id which played the item</summary>
        public int? DeviceID { get; set; }
        /// <summary>The key for this individual history item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HistoryKey { get; set; }
#nullable restore
#else
        public string HistoryKey { get; set; }
#endif
        /// <summary>The metadata key for the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The library section id containing the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LibrarySectionID { get; set; }
#nullable restore
#else
        public string LibrarySectionID { get; set; }
#endif
        /// <summary>The originally available at of the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginallyAvailableAt { get; set; }
#nullable restore
#else
        public string OriginallyAvailableAt { get; set; }
#endif
        /// <summary>The rating key for the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RatingKey { get; set; }
#nullable restore
#else
        public string RatingKey { get; set; }
#endif
        /// <summary>The thumb of the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Thumb { get; set; }
#nullable restore
#else
        public string Thumb { get; set; }
#endif
        /// <summary>The title of the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The metadata type of the item played</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The time when the item was played</summary>
        public int? ViewedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Status.Sessions.History.Item.WithHistoryGetResponse_MediaContainer_Metadata"/> and sets the default values.
        /// </summary>
        public WithHistoryGetResponse_MediaContainer_Metadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Status.Sessions.History.Item.WithHistoryGetResponse_MediaContainer_Metadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Status.Sessions.History.Item.WithHistoryGetResponse_MediaContainer_Metadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Status.Sessions.History.Item.WithHistoryGetResponse_MediaContainer_Metadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountID", n => { AccountID = n.GetIntValue(); } },
                { "deviceID", n => { DeviceID = n.GetIntValue(); } },
                { "historyKey", n => { HistoryKey = n.GetStringValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "librarySectionID", n => { LibrarySectionID = n.GetStringValue(); } },
                { "originallyAvailableAt", n => { OriginallyAvailableAt = n.GetStringValue(); } },
                { "ratingKey", n => { RatingKey = n.GetStringValue(); } },
                { "thumb", n => { Thumb = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "viewedAt", n => { ViewedAt = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountID", AccountID);
            writer.WriteIntValue("deviceID", DeviceID);
            writer.WriteStringValue("historyKey", HistoryKey);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("librarySectionID", LibrarySectionID);
            writer.WriteStringValue("originallyAvailableAt", OriginallyAvailableAt);
            writer.WriteStringValue("ratingKey", RatingKey);
            writer.WriteStringValue("thumb", Thumb);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("viewedAt", ViewedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
