// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Models;
using Soenneker.Plex.OpenApiClient.PlayQueues.Item.Items;
using Soenneker.Plex.OpenApiClient.PlayQueues.Item.Reset;
using Soenneker.Plex.OpenApiClient.PlayQueues.Item.Shuffle;
using Soenneker.Plex.OpenApiClient.PlayQueues.Item.Unshuffle;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.PlayQueues.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \playQueues\{playQueueId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPlayQueueItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The items property</summary>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Items.ItemsRequestBuilder Items
        {
            get => new global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset property</summary>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Reset.ResetRequestBuilder Reset
        {
            get => new global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Reset.ResetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shuffle property</summary>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Shuffle.ShuffleRequestBuilder Shuffle
        {
            get => new global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Shuffle.ShuffleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unshuffle property</summary>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Unshuffle.UnshuffleRequestBuilder Unshuffle
        {
            get => new global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.Unshuffle.UnshuffleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPlayQueueItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playQueues/{playQueueId}{?center*,includeAfter*,includeBefore*,next*,own*,playlistID*,uri*,window*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPlayQueueItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playQueues/{playQueueId}{?center*,includeAfter*,includeBefore*,next*,own*,playlistID*,uri*,window*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves the play queue, centered at current item. This can be treated as a regular container by play queue-oblivious clients, but they may wish to request a large window onto the queue since they won&apos;t know to refresh.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata?> GetAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata> GetAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Adds an item to a play queue (e.g. party mode). Increments the version of the play queue. Takes the following parameters (`uri` and `playlistID` are mutually exclusive). Returns the modified play queue.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata?> PutAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata> PutAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the play queue, centered at current item. This can be treated as a regular container by play queue-oblivious clients, but they may wish to request a large window onto the queue since they won&apos;t know to refresh.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Adds an item to a play queue (e.g. party mode). Increments the version of the play queue. Takes the following parameters (`uri` and `playlistID` are mutually exclusive). Returns the modified play queue.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves the play queue, centered at current item. This can be treated as a regular container by play queue-oblivious clients, but they may wish to request a large window onto the queue since they won&apos;t know to refresh.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPlayQueueItemRequestBuilderGetQueryParameters 
        {
            /// <summary>The play queue item ID for the center of the window - this doesn&apos;t change the current selected item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("center")]
            public string? Center { get; set; }
#nullable restore
#else
            [QueryParameter("center")]
            public string Center { get; set; }
#endif
            /// <summary>Whether to include the items after the center (if 0, center is not included either), defaults to 1.</summary>
            [QueryParameter("includeAfter")]
            public int? IncludeAfter { get; set; }
            /// <summary>Whether to include the items before the center (if 0, center is not included either), defaults to 1.</summary>
            [QueryParameter("includeBefore")]
            public int? IncludeBefore { get; set; }
            /// <summary>If the server should transfer ownership to the requesting client (used in remote control scenarios).</summary>
            [QueryParameter("own")]
            public int? Own { get; set; }
            /// <summary>How many items on each side of the center of the window</summary>
            [QueryParameter("window")]
            public int? Window { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPlayQueueItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Adds an item to a play queue (e.g. party mode). Increments the version of the play queue. Takes the following parameters (`uri` and `playlistID` are mutually exclusive). Returns the modified play queue.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPlayQueueItemRequestBuilderPutQueryParameters 
        {
            /// <summary>Play this item next (defaults to 0 - queueing at the end of manually queued items).</summary>
            [QueryParameter("next")]
            public int? Next { get; set; }
            /// <summary>The ID of the playlist to add to the playQueue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("playlistID")]
            public string? PlaylistID { get; set; }
#nullable restore
#else
            [QueryParameter("playlistID")]
            public string PlaylistID { get; set; }
#endif
            /// <summary>The content URI for what we&apos;re adding to the queue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("uri")]
            public string? Uri { get; set; }
#nullable restore
#else
            [QueryParameter("uri")]
            public string Uri { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPlayQueueItemRequestBuilderPutRequestConfiguration : RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder.WithPlayQueueItemRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
