// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Models;
using Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Item;
using Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Items;
using Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Move;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \playlists\{playlistId}\items\{generator-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GeneratorItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The items property</summary>
        public global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Items.ItemsRequestBuilder Items
        {
            get => new global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The move property</summary>
        public global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Move.MoveRequestBuilder Move
        {
            get => new global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Move.MoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Plex.OpenApiClient.playlists.item.items.item.item collection</summary>
        /// <param name="position">The metadata item ID to act on</param>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Item.WithMetadataItemRequestBuilder"/></returns>
        public global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Item.WithMetadataItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("metadataId", position);
                return new global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Item.WithMetadataItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeneratorItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlistId}/items/{generator%2Did}{?Item*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeneratorItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlistId}/items/{generator%2Did}{?Item*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes an item from a playlist. Only works with dumb playlists.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a playlist&apos;s generator.  Only used for optimized versions
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorGetResponse>(requestInfo, global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Modify a playlist generator.  Only used for optimizer
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata?> PutAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder.GeneratorItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata> PutAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder.GeneratorItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata>(requestInfo, global::Soenneker.Plex.OpenApiClient.Models.MediaContainerWithPlaylistMetadata.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes an item from a playlist. Only works with dumb playlists.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get a playlist&apos;s generator.  Only used for optimized versions
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Modify a playlist generator.  Only used for optimizer
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder.GeneratorItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder.GeneratorItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.GeneratorItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Modify a playlist generator.  Only used for optimizer
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GeneratorItemRequestBuilderPutQueryParameters 
        {
            /// <summary>Note: OpenAPI cannot properly render this query parameter example ([See GHI](https://github.com/OAI/OpenAPI-Specification/issues/1706)).  It should be rendered as:Item[type]=42&amp;Item[title]=Jack-Jack Attack&amp;Item[target]=&amp;Item[targetTagID]=1&amp;Item[locationID]=-1&amp;Item[Location][uri]=library://82503060-0d68-4603-b594-8b071d54819e/item//library/metadata/146&amp;Item[Policy][scope]=all&amp;Item[Policy][value]=&amp;Item[Policy][unwatched]=0</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Item { get; set; }
#nullable restore
#else
            public string Item { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
