// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb
{
    /// <summary>
    /// Builds and executes requests for operations under \media\grabbers\devices\{deviceId}\thumb
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThumbRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Plex.OpenApiClient.media.grabbers.devices.item.thumb.item collection</summary>
        /// <param name="position">A version number of the thumb used for busting cache</param>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb.Item.WithVersionItemRequestBuilder"/></returns>
        public global::Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb.Item.WithVersionItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("version", position);
                return new global::Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb.Item.WithVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb.ThumbRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThumbRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/grabbers/devices/{deviceId}/thumb", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Media.Grabbers.Devices.Item.Thumb.ThumbRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThumbRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/media/grabbers/devices/{deviceId}/thumb", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
