// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.PlayQueues.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.PlayQueues
{
    /// <summary>
    /// Builds and executes requests for operations under \playQueues
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayQueuesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Plex.OpenApiClient.playQueues.item collection</summary>
        /// <param name="position">The ID of the play queue.</param>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder"/></returns>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("playQueueId", position);
                return new global::Soenneker.Plex.OpenApiClient.PlayQueues.Item.WithPlayQueueItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayQueuesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playQueues?type={type}{&continuous*,extrasPrefixCount*,key*,onDeck*,playlistID*,recursive*,repeat*,shuffle*,uri*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayQueuesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playQueues?type={type}{&continuous*,extrasPrefixCount*,key*,onDeck*,playlistID*,recursive*,repeat*,shuffle*,uri*}", rawUrl)
        {
        }
        /// <summary>
        /// Makes a new play queue for a device. The source of the playqueue can either be a URI, or a playlist. The response is a media container with the initial items in the queue. Each item in the queue will be a regular item but with `playQueueItemID` - a unique ID since the queue could have repeated items with the same `ratingKey`.Note: Either `uri` or `playlistID` must be specified
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesPostResponse?> PostAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder.PlayQueuesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesPostResponse> PostAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder.PlayQueuesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesPostResponse>(requestInfo, global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Makes a new play queue for a device. The source of the playqueue can either be a URI, or a playlist. The response is a media container with the initial items in the queue. Each item in the queue will be a regular item but with `playQueueItemID` - a unique ID since the queue could have repeated items with the same `ratingKey`.Note: Either `uri` or `playlistID` must be specified
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder.PlayQueuesRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder.PlayQueuesRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.PlayQueues.PlayQueuesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Makes a new play queue for a device. The source of the playqueue can either be a URI, or a playlist. The response is a media container with the initial items in the queue. Each item in the queue will be a regular item but with `playQueueItemID` - a unique ID since the queue could have repeated items with the same `ratingKey`.Note: Either `uri` or `playlistID` must be specified
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PlayQueuesRequestBuilderPostQueryParameters 
        {
            /// <summary>Whether to create a continuous play queue (e.g. from an episode), defaults to 0.</summary>
            [QueryParameter("continuous")]
            public int? Continuous { get; set; }
            /// <summary>Number of trailers to prepend a movie with not including the pre-roll. If omitted the pre-roll will not be returned in the play queue. When resuming a movie `extrasPrefixCount` should be omitted as a parameter instead of passing 0.</summary>
            [QueryParameter("extrasPrefixCount")]
            public int? ExtrasPrefixCount { get; set; }
            /// <summary>The key of the first item to play, defaults to the first in the play queue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("key")]
            public string? Key { get; set; }
#nullable restore
#else
            [QueryParameter("key")]
            public string Key { get; set; }
#endif
            /// <summary>Only applies to queues of type show or seasons, whether to return a queue that is started on the On Deck episode if one exists. Otherwise begins the play queue on the beginning of the show or season.</summary>
            [QueryParameter("onDeck")]
            public int? OnDeck { get; set; }
            /// <summary>the ID of the playlist we&apos;re playing.</summary>
            [QueryParameter("playlistID")]
            public int? PlaylistID { get; set; }
            /// <summary>Only applies to queues of type photo, whether to retrieve all descendent photos from an album or section, defaults to 1.</summary>
            [QueryParameter("recursive")]
            public int? Recursive { get; set; }
            /// <summary>If the PQ is bigger than the window, fill any empty space with wraparound items, defaults to 0.</summary>
            [QueryParameter("repeat")]
            public int? Repeat { get; set; }
            /// <summary>Whether to shuffle the playlist, defaults to 0.</summary>
            [QueryParameter("shuffle")]
            public int? Shuffle { get; set; }
            /// <summary>The type of play queue to create</summary>
            [QueryParameter("type")]
            public global::Soenneker.Plex.OpenApiClient.PlayQueues.PostTypeQueryParameterType? Type { get; set; }
            /// <summary>The content URI for what we&apos;re playing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("uri")]
            public string? Uri { get; set; }
#nullable restore
#else
            [QueryParameter("uri")]
            public string Uri { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
