// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Player.Playback;
using Soenneker.Plex.OpenApiClient.Player.Resources;
using Soenneker.Plex.OpenApiClient.Player.Timeline;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Player
{
    /// <summary>
    /// Builds and executes requests for operations under \player
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The playback property</summary>
        public global::Soenneker.Plex.OpenApiClient.Player.Playback.PlaybackRequestBuilder Playback
        {
            get => new global::Soenneker.Plex.OpenApiClient.Player.Playback.PlaybackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resources property</summary>
        public global::Soenneker.Plex.OpenApiClient.Player.Resources.ResourcesRequestBuilder Resources
        {
            get => new global::Soenneker.Plex.OpenApiClient.Player.Resources.ResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timeline property</summary>
        public global::Soenneker.Plex.OpenApiClient.Player.Timeline.TimelineRequestBuilder Timeline
        {
            get => new global::Soenneker.Plex.OpenApiClient.Player.Timeline.TimelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/player", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
