// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.IndexM3u8;
using Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \livetv\sessions\{sessionId}\{consumerId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConsumerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The indexM3u8 property</summary>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.IndexM3u8.IndexM3u8RequestBuilder IndexM3u8
        {
            get => new global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.IndexM3u8.IndexM3u8RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Plex.OpenApiClient.livetv.sessions.item.item.item collection</summary>
        /// <param name="position">The segment id</param>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.Item.WithSegmentItemRequestBuilder"/></returns>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.Item.WithSegmentItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("segmentId", position);
                return new global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.Item.WithSegmentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.WithConsumerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConsumerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv/sessions/{sessionId}/{consumerId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Sessions.Item.Item.WithConsumerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConsumerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv/sessions/{sessionId}/{consumerId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
