// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Item.Colon.Transcode.Universal.Subtitles
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetProtocolQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "hls")]
        #pragma warning disable CS1591
        Hls,
        #pragma warning restore CS1591
        [EnumMember(Value = "dash")]
        #pragma warning disable CS1591
        Dash,
        #pragma warning restore CS1591
    }
}
