// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Playlists.Item.Items.Item.Items
{
    /// <summary>The error which could have occurred (or `good`)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ItemsGetResponse_MediaContainer_Metadata_processingStateContext
    {
        [EnumMember(Value = "good")]
        #pragma warning disable CS1591
        Good,
        #pragma warning restore CS1591
        [EnumMember(Value = "sourceFileUnavailable")]
        #pragma warning disable CS1591
        SourceFileUnavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "sourceFileMetadataError")]
        #pragma warning disable CS1591
        SourceFileMetadataError,
        #pragma warning restore CS1591
        [EnumMember(Value = "clientProfileError")]
        #pragma warning disable CS1591
        ClientProfileError,
        #pragma warning restore CS1591
        [EnumMember(Value = "ioError")]
        #pragma warning disable CS1591
        IoError,
        #pragma warning restore CS1591
        [EnumMember(Value = "transcoderError")]
        #pragma warning disable CS1591
        TranscoderError,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownError")]
        #pragma warning disable CS1591
        UnknownError,
        #pragma warning restore CS1591
        [EnumMember(Value = "mediaAnalysisError")]
        #pragma warning disable CS1591
        MediaAnalysisError,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloadFailed")]
        #pragma warning disable CS1591
        DownloadFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "accessDenied")]
        #pragma warning disable CS1591
        AccessDenied,
        #pragma warning restore CS1591
        [EnumMember(Value = "cannotTranscode")]
        #pragma warning disable CS1591
        CannotTranscode,
        #pragma warning restore CS1591
        [EnumMember(Value = "codecInstallError")]
        #pragma warning disable CS1591
        CodecInstallError,
        #pragma warning restore CS1591
    }
}
