// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Plex.OpenApiClient.Updater.Status
{
    /// <summary>The status of this update.- available - This release is available- downloading - This release is downloading- downloaded - This release has been downloaded- installing - This release is installing- tonight - This release will be installed tonight- skipped - This release has been skipped- error - This release has an error- notify - This release is only notifying it is available (typically because it cannot be installed on this setup)- done - This release is complete</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StatusGetResponse_MediaContainer_Release_state
    {
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloading")]
        #pragma warning disable CS1591
        Downloading,
        #pragma warning restore CS1591
        [EnumMember(Value = "downloaded")]
        #pragma warning disable CS1591
        Downloaded,
        #pragma warning restore CS1591
        [EnumMember(Value = "installing")]
        #pragma warning disable CS1591
        Installing,
        #pragma warning restore CS1591
        [EnumMember(Value = "tonight")]
        #pragma warning disable CS1591
        Tonight,
        #pragma warning restore CS1591
        [EnumMember(Value = "skipped")]
        #pragma warning disable CS1591
        Skipped,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "notify")]
        #pragma warning disable CS1591
        Notify,
        #pragma warning restore CS1591
        [EnumMember(Value = "done")]
        #pragma warning disable CS1591
        Done,
        #pragma warning restore CS1591
    }
}
