// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Users
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsersGetResponse_MediaContainer_User_Server : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allLibraries property</summary>
        public int? AllLibraries { get; set; }
        /// <summary>Unique ID of the server of the connected user</summary>
        public int? Id { get; set; }
        /// <summary>Unix epoch datetime in seconds</summary>
        public long? LastSeenAt { get; set; }
        /// <summary>Machine identifier of the Plex server.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MachineIdentifier { get; set; }
#nullable restore
#else
        public string MachineIdentifier { get; set; }
#endif
        /// <summary>Name of the Plex server of the connected user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Number of libraries in the server this user has access to.</summary>
        public int? NumLibraries { get; set; }
        /// <summary>The owned property</summary>
        public int? Owned { get; set; }
        /// <summary>The pending property</summary>
        public int? Pending { get; set; }
        /// <summary>ID of the actual Plex server.</summary>
        public int? ServerId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Users.UsersGetResponse_MediaContainer_User_Server"/> and sets the default values.
        /// </summary>
        public UsersGetResponse_MediaContainer_User_Server()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Users.UsersGetResponse_MediaContainer_User_Server"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Plex.OpenApiClient.Users.UsersGetResponse_MediaContainer_User_Server CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Users.UsersGetResponse_MediaContainer_User_Server();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allLibraries", n => { AllLibraries = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lastSeenAt", n => { LastSeenAt = n.GetLongValue(); } },
                { "machineIdentifier", n => { MachineIdentifier = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "numLibraries", n => { NumLibraries = n.GetIntValue(); } },
                { "owned", n => { Owned = n.GetIntValue(); } },
                { "pending", n => { Pending = n.GetIntValue(); } },
                { "serverId", n => { ServerId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("allLibraries", AllLibraries);
            writer.WriteIntValue("id", Id);
            writer.WriteLongValue("lastSeenAt", LastSeenAt);
            writer.WriteStringValue("machineIdentifier", MachineIdentifier);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("numLibraries", NumLibraries);
            writer.WriteIntValue("owned", Owned);
            writer.WriteIntValue("pending", Pending);
            writer.WriteIntValue("serverId", ServerId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
