// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Colon.Eventsource;
using Soenneker.Plex.OpenApiClient.Colon.Prefs;
using Soenneker.Plex.OpenApiClient.Colon.Rate;
using Soenneker.Plex.OpenApiClient.Colon.Scrobble;
using Soenneker.Plex.OpenApiClient.Colon.Timeline;
using Soenneker.Plex.OpenApiClient.Colon.Unscrobble;
using Soenneker.Plex.OpenApiClient.Colon.Websocket;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Colon
{
    /// <summary>
    /// Builds and executes requests for operations under \:
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The eventsource property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Eventsource.EventsourceRequestBuilder Eventsource
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Eventsource.EventsourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The prefs property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Prefs.PrefsRequestBuilder Prefs
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Prefs.PrefsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rate property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Rate.RateRequestBuilder Rate
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Rate.RateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scrobble property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Scrobble.ScrobbleRequestBuilder Scrobble
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Scrobble.ScrobbleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timeline property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder Timeline
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Timeline.TimelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unscrobble property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Unscrobble.UnscrobbleRequestBuilder Unscrobble
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Unscrobble.UnscrobbleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The websocket property</summary>
        public global::Soenneker.Plex.OpenApiClient.Colon.Websocket.WebsocketRequestBuilder Websocket
        {
            get => new global::Soenneker.Plex.OpenApiClient.Colon.Websocket.WebsocketRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Colon.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/:", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Colon.RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/:", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
