// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Plex.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Plex.OpenApiClient.Status.Sessions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SessionsGetResponse_MediaContainer_Metadata : global::Soenneker.Plex.OpenApiClient.Models.Metadata, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Information about the player being used for playback</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.Player? Player { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.Player Player { get; set; }
#endif
        /// <summary>Information about the playback session</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.Session? Session { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.Session Session { get; set; }
#endif
        /// <summary>The user playing the content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Plex.OpenApiClient.Models.User? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Plex.OpenApiClient.Models.User User { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Plex.OpenApiClient.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Plex.OpenApiClient.Status.Sessions.SessionsGetResponse_MediaContainer_Metadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "Player", n => { Player = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.Player>(global::Soenneker.Plex.OpenApiClient.Models.Player.CreateFromDiscriminatorValue); } },
                { "Session", n => { Session = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.Session>(global::Soenneker.Plex.OpenApiClient.Models.Session.CreateFromDiscriminatorValue); } },
                { "User", n => { User = n.GetObjectValue<global::Soenneker.Plex.OpenApiClient.Models.User>(global::Soenneker.Plex.OpenApiClient.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.Player>("Player", Player);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.Session>("Session", Session);
            writer.WriteObjectValue<global::Soenneker.Plex.OpenApiClient.Models.User>("User", User);
        }
    }
}
#pragma warning restore CS0618
