// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Hubs.Home.RecentlyAdded;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Plex.OpenApiClient.Hubs.Home
{
    /// <summary>
    /// Builds and executes requests for operations under \hubs\home
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HomeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The recentlyAdded property</summary>
        public global::Soenneker.Plex.OpenApiClient.Hubs.Home.RecentlyAdded.RecentlyAddedRequestBuilder RecentlyAdded
        {
            get => new global::Soenneker.Plex.OpenApiClient.Hubs.Home.RecentlyAdded.RecentlyAddedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Hubs.Home.HomeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HomeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs/home", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Hubs.Home.HomeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HomeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hubs/home", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
