// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Channels;
using Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Devices;
using Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Lineups;
using Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Prefs;
using Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.ReloadGuide;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \livetv\dvrs\{dvrId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDvrItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The channels property</summary>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lineups property</summary>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Lineups.LineupsRequestBuilder Lineups
        {
            get => new global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Lineups.LineupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The prefs property</summary>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Prefs.PrefsRequestBuilder Prefs
        {
            get => new global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.Prefs.PrefsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reloadGuide property</summary>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.ReloadGuide.ReloadGuideRequestBuilder ReloadGuide
        {
            get => new global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.ReloadGuide.ReloadGuideRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDvrItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv/dvrs/{dvrId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDvrItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/livetv/dvrs/{dvrId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a single DVR by its id (key)
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a single DVR by its id (key)
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrGetResponse?> GetAsWithDvrGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrGetResponse> GetAsWithDvrGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrGetResponse>(requestInfo, global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a single DVR by its id (key)
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithDvrGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrResponse>(requestInfo, global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a single DVR by its id (key)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/html");
            return requestInfo;
        }
        /// <summary>
        /// Get a single DVR by its id (key)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.Livetv.Dvrs.Item.WithDvrItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDvrItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDvrItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
