// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image
{
    /// <summary>
    /// Builds and executes requests for operations under \services\ultrablur\image
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/services/ultrablur/image{?bottomLeft*,bottomRight*,height*,noise*,topLeft*,topRight*,width*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/services/ultrablur/image{?bottomLeft*,bottomRight*,height*,noise*,topLeft*,topRight*,width*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a server-side generated UltraBlur image based on the provided color inputs. Clients should always call this via the photo transcoder endpoint.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a server-side generated UltraBlur image based on the provided color inputs. Clients should always call this via the photo transcoder endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "image/png");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Plex.OpenApiClient.Services.Ultrablur.Image.ImageRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a server-side generated UltraBlur image based on the provided color inputs. Clients should always call this via the photo transcoder endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImageRequestBuilderGetQueryParameters 
        {
            /// <summary>The base color (hex) for the bottom left quadrant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bottomLeft")]
            public string? BottomLeft { get; set; }
#nullable restore
#else
            [QueryParameter("bottomLeft")]
            public string BottomLeft { get; set; }
#endif
            /// <summary>The base color (hex) for the bottom right quadrant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bottomRight")]
            public string? BottomRight { get; set; }
#nullable restore
#else
            [QueryParameter("bottomRight")]
            public string BottomRight { get; set; }
#endif
            /// <summary>Height in pixels for the image.</summary>
            [QueryParameter("height")]
            public int? Height { get; set; }
            /// <summary>Whether to add noise to the ouput image. Noise can reduce color banding with the gradients. Image sizes with noise will be larger.</summary>
            [QueryParameter("noise")]
            public int? Noise { get; set; }
            /// <summary>The base color (hex) for the top left quadrant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("topLeft")]
            public string? TopLeft { get; set; }
#nullable restore
#else
            [QueryParameter("topLeft")]
            public string TopLeft { get; set; }
#endif
            /// <summary>The base color (hex) for the top right quadrant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("topRight")]
            public string? TopRight { get; set; }
#nullable restore
#else
            [QueryParameter("topRight")]
            public string TopRight { get; set; }
#endif
            /// <summary>Width in pixels for the image.</summary>
            [QueryParameter("width")]
            public int? Width { get; set; }
        }
    }
}
#pragma warning restore CS0618
